### ISSUE TITLE
uncaught exception when currentWaypoint.path is not defined

### ISSUE THREAD

**Issue by mrsdizzie** [robochase6000/navigation.novaextension#1]
First off, thanks for this extension!

To reproduce when editing a file in a project in Nova,:

 * Open a new empty Nova window using `⌘+Shift+N` 
 * Add Some content to the new window
 * Save the content as a new file

After that, I get an endless loop (presumably every 100ms) of these errors in the extension console:

```
Navigation[10:26:46.136000] Extension encountered an uncaught exception:
/Users/isla/Library/Application Support/Nova/Extensions/robochase6000.navigation/Scripts/main.js (Line 155, Column 44)
TypeError: undefined is not an object (evaluating 'currentWaypoint.path')
    checkCurrentFile@file:///Users/isla/Library/Application%20Support/Nova/Extensions/robochase6000.navigation/Scripts/main.js:155:44
    @file:///Users/isla/Library/Application%20Support/Nova/Extensions/robochase6000.navigation/Scripts/main.js:138:29
```

**Comment by robochase6000** [comment]
thanks for reporting, i’ll take a look today. 

edge case handling around making new files is a little half baked so this isn’t all that surprising :)

**Comment by robochase6000** [comment]
alright this should be fixed.  I've already pushed version 1.1.5 to Nova's Extension Library

Thanks, this was a good catch @mrsdizzie 

Considering this closed 🤞

**Comment by mrsdizzie** [comment]
Looks good, thanks!
